### ISSUE TITLE
Using xo xontrib freezes everything

### ISSUE THREAD

**Issue by airdrik** [scopatz/xo#17]
Recently when I've tried using the xo xontrib in xonsh, it has started just freezing - it doesn't load anything, it just sits there on the line after the command to run xo until I hit ctrl+c to try and close out and try again/something else. Event then hitting ctrl+c doesn't always exit the call to xo and I have to restart xonsh.

I'm not entirely sure what may have caused this, though I suspect it may be something related to upgrading xo from 0.1.11 to 0.1.13

Tested using xonsh 5.2 and 5.3, Ubuntu 14.04, python 3.4, xonsh and xo/exofrills installed using pip (for python 3.4).

I also tried unloading the xo xontrib and running the stand-alone xo command and that works just fine.
Only other xontrib loaded in xonsh is apt_tabcomplete which seems to work just fine as well.

**Comment by scopatz** [comment]
Thanks for pointing this out @airdrik! I have put in a fix to master and put out the 0.1.14 release that includes the fix. Please let me know if you continue to have issues. Otherwise, feel free to close this.

**Comment by airdrik** [comment]
Tested 0.1.14 release and it now works as expected.

Thank you.
