### ISSUE TITLE
Pressing "end" doesn't update column count in the status bar

### ISSUE THREAD

**Issue by therainingmonkey** [scopatz/xo#18]
When pressing 'end' to jump to the end of a line, the column count in the status bar does not update until the cursor next moves with an arrow key press etc.
'home' key works as expected.

Using xo from pip3

**Comment by scopatz** [comment]
Thanks for reporting! I have noticed this issue myself. Pull requests welcome.

**Comment by rovitotv** [comment]
Fixed with PR #29 can @scopatz or @therainingmonkey please close the issue?
