### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by Foadsf** [scopatz/xo#20]
I tried installing it on my mac with pip3. It successfully finished installing but when tried to run I got dependency errors: 

> Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   from collections import deque, Mapping, Sequence

and 

> Traceback (most recent call last):
>   File "/usr/local/bin/xo", line 34, in <module>
>     import urwid
> ModuleNotFoundError: No module named 'urwid'

and 

> Traceback (most recent call last):
>   File "/usr/local/bin/xo", line 36, in <module>
>     import pygments_cache
> ModuleNotFoundError: No module named 'pygments_cache'

The last two I could solve by `pip install urwid and pygments_cache`. But the first one I don't know how to solve.

**Comment by scopatz** [comment]
Hi there, thanks for reporting.  The first issue is an easy fix.  I'll put in a change and a release soon

**Comment by scopatz** [comment]
A fix has been pushed up and v0.3.1 released!

**Comment by scopatz** [comment]
Thanks for reporting!

**Comment by michaelaye** [comment]
`urwid` case isn't fixed yet:

```bash
$ xo --version                                                                 (py36)
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py36/bin/xo", line 35, in <module>
    import urwid
ModuleNotFoundError: No module named 'urwid'
klay6683@MacL2938|~/D/src
$ pip show exofrills                                                           (py36)
Name: exofrills
Version: 0.3.1
Summary: exofrills text editor
Home-page: http://exofrills.org/
Author: Anthony Scopatz
Author-email: scopatz@gmail.com
License: UNKNOWN
Location: /Users/klay6683/miniconda3/envs/py36/lib/python3.6/site-packages
Requires:
Required-by:
```

**Comment by scopatz** [comment]
Happy to have a PR fix here!
